"""empty message

Revision ID: 19c24afa4b5b
Revises: 54a79b60256c
Create Date: 2019-06-25 12:39:19.089757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c24afa4b5b'
down_revision = '54a79b60256c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'num')
    # ### end Alembic commands ###
