"""empty message

Revision ID: 219eb53755e9
Revises: 
Create Date: 2019-06-22 10:04:57.205832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219eb53755e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=2000), nullable=True),
    sa.Column('picture', sa.String(length=100), nullable=True),
    sa.Column('article_class', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_class'], ['article_class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('article_class')
    # ### end Alembic commands ###
