"""empty message

Revision ID: 54a79b60256c
Revises: 0b3f72012759
Create Date: 2019-06-23 22:59:56.888714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54a79b60256c'
down_revision = '0b3f72012759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('Introduction', sa.String(length=100), nullable=True))
    op.drop_column('article', 'desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('desc', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('article', 'Introduction')
    # ### end Alembic commands ###
