"""empty message

Revision ID: 5fd0d2a252aa
Revises: 19c24afa4b5b
Create Date: 2019-06-25 13:12:30.262100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fd0d2a252aa'
down_revision = '19c24afa4b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'num')
    op.add_column('article_class', sa.Column('num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_class', 'num')
    op.add_column('article', sa.Column('num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
