"""empty message

Revision ID: ab685a9c2441
Revises: 5fd0d2a252aa
Create Date: 2019-06-27 00:43:05.446023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab685a9c2441'
down_revision = '5fd0d2a252aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'Introduction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('Introduction', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
